use_frameworks!
platform :ios, '9.0'

pod 'IQKeyboardManagerSwift'
pod 'Kingfisher'
pod 'GoogleSignIn'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'

target 'Friendly Chat' do
end
